INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text) VALUES
    ('zh_Hans_CN', 'LOC_CIVILIZATION_ELPIS_PROTOCOL_NAME', '厄尔庇斯协议'),
    ('zh_Hans_CN', 'LOC_CIVILIZATION_ELPIS_PROTOCOL_DESCRIPTION', '厄尔庇斯协议'),
    ('zh_Hans_CN', 'LOC_CIVILIZATION_ELPIS_PROTOCOL_ADJECTIVE', '厄尔庇斯协议的'),
    ('zh_Hans_CN', 'LOC_TRAIT_CIVILIZATION_ELPIS_PROTOCOL_NAME', '感染样本管制'),
    ('zh_Hans_CN', 'LOC_TRAIT_CIVILIZATION_ELPIS_PROTOCOL_DESCRIPTION', '偏好靠近河流与丘陵出生。开局触发“文字”尤里卡。特色区域“方舟”替代学院，方舟的 [ICON_Science] 科技相邻加成也提供等额 [ICON_Production] 生产力。研究“文字”后，击杀蛮族单位可获得战略资源感染者血液，再通过方舟项目转化为战斗强化、科技值、大科学家点数或尤里卡。'),

    ('zh_Hans_CN', 'LOC_LEADER_GRACE_ASHCROFT_NAME', '格蕾丝·阿什克罗夫特'),
    ('zh_Hans_CN', 'LOC_TRAIT_LEADER_GRACE_ASHCROFT_NAME', '隔离线调查员'),
    ('zh_Hans_CN', 'LOC_TRAIT_LEADER_GRACE_ASHCROFT_DESCRIPTION', '清剿蛮族威胁并回收感染样本。通过短周期城市项目将感染者血液制备为溶血剂、稳定剂、类固醇，或转化为科研成果。'),
    ('zh_Hans_CN', 'LOC_PEDIA_LEADERS_PAGE_LEADER_GRACE_ASHCROFT_QUOTE', '每一份样本都是下一次生还的证据。'),
    ('zh_Hans_CN', 'LOC_LOADING_INFO_LEADER_GRACE_ASHCROFT', '格蕾丝·阿什克罗夫特，隔离线的灯仍未熄灭。清剿失控威胁，回收危险样本，用方舟把恐惧转化为秩序、治疗和真相。'),

    ('zh_Hans_CN', 'LOC_CITY_NAME_RHODES_HILL', '罗兹山'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_ELPIS_SITE', '厄尔庇斯站点'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_CONTAINMENT_ZONE', '隔离区'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_ASHCROFT_STATION', '阿什克罗夫特站'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_QUARANTINE_LINE', '封锁线'),

    ('zh_Hans_CN', 'LOC_RESOURCE_INFECTED_BLOOD_NAME', '感染者血液'),

    ('zh_Hans_CN', 'LOC_DISTRICT_GRACE_ARK_NAME', '方舟'),
    ('zh_Hans_CN', 'LOC_DISTRICT_GRACE_ARK_DESCRIPTION', '厄尔庇斯协议特色科技区域，替代学院。方舟的 [ICON_Science] 科技相邻加成也提供等额 [ICON_Production] 生产力。相邻市中心提供 +2 [ICON_Science] 科技值；每个相邻区域和每个相邻改良设施提供 +1 [ICON_Science] 科技值。方舟还为相邻专业区域提供 +1 对应主产出相邻加成，并拥有军营式防御能力。'),
    ('zh_Hans_CN', 'LOC_TRAIT_DISTRICT_GRACE_ARK_NAME', '{LOC_DISTRICT_GRACE_ARK_NAME}'),
    ('zh_Hans_CN', 'LOC_TRAIT_DISTRICT_GRACE_ARK_DESCRIPTION', '{LOC_DISTRICT_GRACE_ARK_DESCRIPTION}'),

    ('zh_Hans_CN', 'LOC_GRACE_ARK_PRODUCTION_MIRROR_DESCRIPTION', '+{1_Num} [ICON_Production] 生产力，来自方舟科技相邻加成。'),
    ('zh_Hans_CN', 'LOC_GRACE_ARK_CITY_CENTER_SCIENCE_DESCRIPTION', '+{1_Num} [ICON_Science] 科技值，来自相邻市中心。'),
    ('zh_Hans_CN', 'LOC_GRACE_ARK_CITY_CENTER_PRODUCTION_DESCRIPTION', '+{1_Num} [ICON_Production] 生产力，来自相邻市中心。'),
    ('zh_Hans_CN', 'LOC_GRACE_ARK_DISTRICT_SCIENCE_DESCRIPTION', '+{1_Num} [ICON_Science] 科技值，来自相邻区域。'),
    ('zh_Hans_CN', 'LOC_GRACE_ARK_DISTRICT_PRODUCTION_DESCRIPTION', '+{1_Num} [ICON_Production] 生产力，来自相邻区域。'),
    ('zh_Hans_CN', 'LOC_GRACE_ARK_IMPROVEMENT_SCIENCE_DESCRIPTION', '每个相邻改良设施 +{1_Num} [ICON_Science] 科技值。'),
    ('zh_Hans_CN', 'LOC_GRACE_ARK_IMPROVEMENT_PRODUCTION_DESCRIPTION', '每个相邻改良设施 +{1_Num} [ICON_Production] 生产力。'),
    ('zh_Hans_CN', 'LOC_GRACE_ARK_TO_SCIENCE_DESCRIPTION', '+{1_Num} [ICON_Science] 科技值，来自相邻方舟。'),
    ('zh_Hans_CN', 'LOC_GRACE_ARK_TO_FAITH_DESCRIPTION', '+{1_Num} [ICON_Faith] 信仰值，来自相邻方舟。'),
    ('zh_Hans_CN', 'LOC_GRACE_ARK_TO_CULTURE_DESCRIPTION', '+{1_Num} [ICON_Culture] 文化值，来自相邻方舟。'),
    ('zh_Hans_CN', 'LOC_GRACE_ARK_TO_GOLD_DESCRIPTION', '+{1_Num} [ICON_Gold] 金币，来自相邻方舟。'),
    ('zh_Hans_CN', 'LOC_GRACE_ARK_TO_PRODUCTION_DESCRIPTION', '+{1_Num} [ICON_Production] 生产力，来自相邻方舟。'),

    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_HEMOLYTIC_1_NAME', '溶血剂制备 I'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_HEMOLYTIC_1_SHORT_NAME', '溶血剂 I'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_HEMOLYTIC_1_DESCRIPTION', '消耗 1 感染者血液，将溶血剂提升至 I 级。所有单位对蛮族单位 +5 [ICON_Strength] 战斗力。'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_HEMOLYTIC_2_NAME', '溶血剂制备 II'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_HEMOLYTIC_2_SHORT_NAME', '溶血剂 II'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_HEMOLYTIC_2_DESCRIPTION', '消耗 1 感染者血液，将溶血剂提升至 II 级。高等级覆盖低等级；所有单位对蛮族单位 +10 [ICON_Strength] 战斗力。'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_HEMOLYTIC_3_NAME', '溶血剂制备 III'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_HEMOLYTIC_3_SHORT_NAME', '溶血剂 III'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_HEMOLYTIC_3_DESCRIPTION', '消耗 1 感染者血液，将溶血剂提升至 III 级。高等级覆盖低等级；所有单位对蛮族单位 +15 [ICON_Strength] 战斗力。'),

    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STABILIZER_1_NAME', '稳定剂制备 I'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STABILIZER_1_SHORT_NAME', '稳定剂 I'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STABILIZER_1_DESCRIPTION', '消耗 1 感染者血液，将稳定剂提升至 I 级。所有单位 +5 [ICON_Strength] 战斗力。'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STABILIZER_2_NAME', '稳定剂制备 II'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STABILIZER_2_SHORT_NAME', '稳定剂 II'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STABILIZER_2_DESCRIPTION', '消耗 1 感染者血液，将稳定剂提升至 II 级。高等级覆盖低等级；所有单位 +10 [ICON_Strength] 战斗力。'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STABILIZER_3_NAME', '稳定剂制备 III'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STABILIZER_3_SHORT_NAME', '稳定剂 III'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STABILIZER_3_DESCRIPTION', '消耗 1 感染者血液，将稳定剂提升至 III 级。高等级覆盖低等级；所有单位 +15 [ICON_Strength] 战斗力。'),

    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STEROID_1_NAME', '类固醇制备 I'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STEROID_1_SHORT_NAME', '类固醇 I'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STEROID_1_DESCRIPTION', '消耗 1 感染者血液，将类固醇提升至 I 级。每回合开始时所有受伤单位恢复 +5 [ICON_Damaged] 生命值。'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STEROID_2_NAME', '类固醇制备 II'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STEROID_2_SHORT_NAME', '类固醇 II'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STEROID_2_DESCRIPTION', '消耗 1 感染者血液，将类固醇提升至 II 级。每回合开始时所有受伤单位恢复 +10 [ICON_Damaged] 生命值。'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STEROID_3_NAME', '类固醇制备 III'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STEROID_3_SHORT_NAME', '类固醇 III'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_STEROID_3_DESCRIPTION', '消耗 1 感染者血液，将类固醇提升至 III 级。每回合开始时所有受伤单位恢复 +15 [ICON_Damaged] 生命值。'),

    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_BLOOD_SAMPLE_ANALYSIS_NAME', '血液样本分析'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_BLOOD_SAMPLE_ANALYSIS_SHORT_NAME', '样本分析'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_BLOOD_SAMPLE_ANALYSIS_DESCRIPTION', '消耗 1 感染者血液，随机触发一个当前时代可用尤里卡。如果没有可触发的尤里卡，则获得科技值补偿。'),

    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_ABNORMAL_PATHOLOGY_NAME', '异常病理研究'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_ABNORMAL_PATHOLOGY_SHORT_NAME', '病理研究'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_ABNORMAL_PATHOLOGY_DESCRIPTION', '消耗 1 感染者血液，获得大科学家点数。奖励随时代提高。'),

    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_CONTAINMENT_REVIEW_NAME', '隔离协议复盘'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_CONTAINMENT_REVIEW_SHORT_NAME', '协议复盘'),
    ('zh_Hans_CN', 'LOC_PROJECT_GRACE_CONTAINMENT_REVIEW_DESCRIPTION', '消耗 1 感染者血液，获得科技值和少量大科学家点数。奖励随时代提高。'),

    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_HEMOLYTIC_1_NAME', '溶血剂 I'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_HEMOLYTIC_1_DESCRIPTION', '对蛮族单位 +5 [ICON_Strength] 战斗力。'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_HEMOLYTIC_2_NAME', '溶血剂 II'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_HEMOLYTIC_2_DESCRIPTION', '对蛮族单位 +10 [ICON_Strength] 战斗力。'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_HEMOLYTIC_3_NAME', '溶血剂 III'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_HEMOLYTIC_3_DESCRIPTION', '对蛮族单位 +15 [ICON_Strength] 战斗力。'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STABILIZER_1_NAME', '稳定剂 I'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STABILIZER_1_DESCRIPTION', '+5 [ICON_Strength] 战斗力。'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STABILIZER_2_NAME', '稳定剂 II'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STABILIZER_2_DESCRIPTION', '+10 [ICON_Strength] 战斗力。'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STABILIZER_3_NAME', '稳定剂 III'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STABILIZER_3_DESCRIPTION', '+15 [ICON_Strength] 战斗力。'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STEROID_1_NAME', '类固醇 I'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STEROID_1_DESCRIPTION', '每回合开始时所有受伤单位恢复 +5 [ICON_Damaged] 生命值。'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STEROID_2_NAME', '类固醇 II'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STEROID_2_DESCRIPTION', '每回合开始时所有受伤单位恢复 +10 [ICON_Damaged] 生命值。'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STEROID_3_NAME', '类固醇 III'),
    ('zh_Hans_CN', 'LOC_ABILITY_GRACE_STEROID_3_DESCRIPTION', '每回合开始时所有受伤单位恢复 +15 [ICON_Damaged] 生命值。'),

    ('zh_Hans_CN', 'LOC_GRACE_HEMOLYTIC_1_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自溶血剂 I（对蛮族）'),
    ('zh_Hans_CN', 'LOC_GRACE_HEMOLYTIC_2_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自溶血剂 II（对蛮族）'),
    ('zh_Hans_CN', 'LOC_GRACE_HEMOLYTIC_3_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自溶血剂 III（对蛮族）'),
    ('zh_Hans_CN', 'LOC_GRACE_STABILIZER_1_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自稳定剂 I'),
    ('zh_Hans_CN', 'LOC_GRACE_STABILIZER_2_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自稳定剂 II'),
    ('zh_Hans_CN', 'LOC_GRACE_STABILIZER_3_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自稳定剂 III'),

    ('zh_Hans_CN', 'LOC_GRACE_NOTIFICATION_BLOOD_GAINED', '获得 {1_num} 感染者血液。当前库存：{2_num}。'),
    ('zh_Hans_CN', 'LOC_GRACE_NOTIFICATION_BLOOD_SPENT', '消耗 {1_num} 感染者血液。剩余库存：{2_num}。'),
    ('zh_Hans_CN', 'LOC_GRACE_NOTIFICATION_PROJECT_CAPPED', '该强化已达到上限，无法继续制备。'),
    ('zh_Hans_CN', 'LOC_GRACE_NOTIFICATION_ENHANCER_GAINED', '获得 {1_Name} 强化（{2_num}/{3_num}）。当前血液：{4_num}。'),
    ('zh_Hans_CN', 'LOC_GRACE_NOTIFICATION_SCIENCE_GAINED', '获得 {1_num} 科技值。当前血液：{2_num}。'),
    ('zh_Hans_CN', 'LOC_GRACE_NOTIFICATION_SCIENTIST_POINTS_GAINED', '获得 {1_num} 大科学家点数。当前血液：{2_num}。'),
    ('zh_Hans_CN', 'LOC_GRACE_NOTIFICATION_EUREKA_TRIGGERED', '触发 {1_Name} 尤里卡。当前血液：{2_num}。'),
    ('zh_Hans_CN', 'LOC_GRACE_NOTIFICATION_WRITING_EUREKA', '方舟协议启动：已触发“文字”尤里卡。'),
    ('zh_Hans_CN', 'LOC_GRACE_NOTIFICATION_EUREKA_FALLBACK', '没有可触发的尤里卡，已转化为 {1_num} 科技值。');
