INSERT OR REPLACE INTO IconDefinitions
    (Name, Atlas, 'Index')
VALUES
    ('ICON_RESOURCE_INFECTED_BLOOD', 'ICON_ATLAS_RESOURCES', 46),
    ('ICON_RESOURCE_INFECTED_BLOOD_FOW', 'ICON_ATLAS_RESOURCES_FOW', 46),
    ('RESOURCE_INFECTED_BLOOD', 'ICON_ATLAS_FONT_ICON_BASELINE_6', 95),
    ('ICON_DISTRICT_GRACE_ARK', 'ICON_ATLAS_DISTRICTS', 2),
    ('ICON_DISTRICT_GRACE_ARK_FOW', 'ICON_ATLAS_DISTRICTS_FOW', 2),
    ('ICON_PROJECT_GRACE_HEMOLYTIC_1', 'ICON_ATLAS_PROJECTS', 16),
    ('ICON_PROJECT_GRACE_HEMOLYTIC_2', 'ICON_ATLAS_PROJECTS', 16),
    ('ICON_PROJECT_GRACE_HEMOLYTIC_3', 'ICON_ATLAS_PROJECTS', 16),
    ('ICON_PROJECT_GRACE_STABILIZER_1', 'ICON_ATLAS_PROJECTS', 16),
    ('ICON_PROJECT_GRACE_STABILIZER_2', 'ICON_ATLAS_PROJECTS', 16),
    ('ICON_PROJECT_GRACE_STABILIZER_3', 'ICON_ATLAS_PROJECTS', 16),
    ('ICON_PROJECT_GRACE_STEROID_1', 'ICON_ATLAS_PROJECTS', 16),
    ('ICON_PROJECT_GRACE_STEROID_2', 'ICON_ATLAS_PROJECTS', 16),
    ('ICON_PROJECT_GRACE_STEROID_3', 'ICON_ATLAS_PROJECTS', 16),
    ('ICON_PROJECT_GRACE_BLOOD_SAMPLE_ANALYSIS', 'ICON_ATLAS_PROJECTS', 16),
    ('ICON_PROJECT_GRACE_ABNORMAL_PATHOLOGY', 'ICON_ATLAS_PROJECTS', 16),
    ('ICON_PROJECT_GRACE_CONTAINMENT_REVIEW', 'ICON_ATLAS_PROJECTS', 16);
