INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text) VALUES
    ('zh_Hans_CN', 'LOC_CIVILIZATION_CHUUNI_SOCIETY_NAME', '极东魔术昼寝结社之夏'),
    ('zh_Hans_CN', 'LOC_CIVILIZATION_CHUUNI_SOCIETY_DESCRIPTION', '极东魔术昼寝结社之夏'),
    ('zh_Hans_CN', 'LOC_CIVILIZATION_CHUUNI_SOCIETY_ADJECTIVE', '极东魔术昼寝结社之夏的'),
    ('zh_Hans_CN', 'LOC_TRAIT_CIVILIZATION_CHUUNI_SOCIETY_NAME', '幻想结社'),
    ('zh_Hans_CN', 'LOC_TRAIT_CIVILIZATION_CHUUNI_SOCIETY_DESCRIPTION', '建立极东魔术昼寝结社并积累中二值。中二值达到1时，军事与宗教战斗力+3；达到20且已创立宗教时额外+2；达到50且已创立宗教时额外+3，最终为+8。'),
    ('zh_Hans_CN', 'LOC_LEADER_RIKKA_TAKANASHI_NAME', '小鸟游六花'),
    ('zh_Hans_CN', 'LOC_TRAIT_LEADER_RIKKA_TAKANASHI_NAME', '探索不可视境界线'),
    ('zh_Hans_CN', 'LOC_TRAIT_LEADER_RIKKA_TAKANASHI_DESCRIPTION', '首次亲自建立沿海城市时获得5点中二值，所有城市永久获得+2宜居度。'),
    ('zh_Hans_CN', 'LOC_PEDIA_LEADERS_PAGE_LEADER_RIKKA_TAKANASHI_QUOTE', '爆裂吧，现实！粉碎吧，精神！'),
    ('zh_Hans_CN', 'LOC_LOADING_INFO_LEADER_RIKKA_TAKANASHI', '邪王真眼将揭开不可视境界线。'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_CHUUNI_CLUBROOM', '结社部室'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_CHUUNI_BOUNDARY', '不可视境界线'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_CHUUNI_NAP_HALL', '昼寝会馆'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_CHUUNI_DARK_FLAME', '暗炎城'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_CHUUNI_MAGIC_CIRCLE', '魔法阵之庭'),
    ('zh_Hans_CN', 'LOC_RESOURCE_CHUUNI_VALUE_NAME', '中二值'),
    ('zh_Hans_CN', 'LOC_RESOURCE_CHUUNI_VALUE_DESCRIPTION', '结社幻想力量的累积值，上限为100。'),
    ('zh_Hans_CN', 'LOC_DISTRICT_CHUUNI_SOCIETY_NAME', '极东魔术昼寝结社'),
    ('zh_Hans_CN', 'LOC_DISTRICT_CHUUNI_SOCIETY_DESCRIPTION', '替代圣地。最终每回合提供2点大预言家点数。只要相邻至少一个学院，自身固定获得+3信仰值；相邻学院获得+2科技值，其他相邻专业区域也获得+2对应主要产出。'),
    ('zh_Hans_CN', 'LOC_TRAIT_DISTRICT_CHUUNI_SOCIETY_NAME', '{LOC_DISTRICT_CHUUNI_SOCIETY_NAME}'),
    ('zh_Hans_CN', 'LOC_TRAIT_DISTRICT_CHUUNI_SOCIETY_DESCRIPTION', '{LOC_DISTRICT_CHUUNI_SOCIETY_DESCRIPTION}'),
    ('zh_Hans_CN', 'LOC_BUILDING_CLUB_MAGIC_CIRCLE_NAME', '部室魔法阵'),
    ('zh_Hans_CN', 'LOC_BUILDING_CLUB_MAGIC_CIRCLE_DESCRIPTION', '替代神龛。+2信仰值、+1宜居度、0维护费，并保留神龛的1点大预言家点数。'),
    ('zh_Hans_CN', 'LOC_TRAIT_BUILDING_CLUB_MAGIC_CIRCLE_NAME', '{LOC_BUILDING_CLUB_MAGIC_CIRCLE_NAME}'),
    ('zh_Hans_CN', 'LOC_TRAIT_BUILDING_CLUB_MAGIC_CIRCLE_DESCRIPTION', '{LOC_BUILDING_CLUB_MAGIC_CIRCLE_DESCRIPTION}'),
    ('zh_Hans_CN', 'LOC_CHUUNI_SOCIETY_TO_SCIENCE_DESCRIPTION', '+{1_Num}科技值，来自相邻极东魔术昼寝结社。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_SOCIETY_TO_CULTURE_DESCRIPTION', '+{1_Num}文化值，来自相邻极东魔术昼寝结社。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_SOCIETY_TO_GOLD_DESCRIPTION', '+{1_Num}金币，来自相邻极东魔术昼寝结社。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_SOCIETY_TO_PRODUCTION_DESCRIPTION', '+{1_Num}生产力，来自相邻极东魔术昼寝结社。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_SOCIETY_TO_FAITH_DESCRIPTION', '+{1_Num}信仰值，来自相邻极东魔术昼寝结社。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_FANTASY_COMBAT_STAGE_1_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自幻想第一阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_FANTASY_COMBAT_STAGE_2_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自幻想第二阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_FANTASY_COMBAT_STAGE_3_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自幻想第三阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STAGE_1_UNLOCKED', '中二值达到1：幻想第一阶段已解锁。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STAGE_2_UNLOCKED', '中二值达到20且已创立宗教：幻想第二阶段已解锁。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STAGE_3_UNLOCKED', '中二值达到50且已创立宗教：幻想第三阶段已解锁。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STAGE_4_UNLOCKED', '中二值达到100且已创立宗教：幻想第四阶段已解锁。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_FIRST_COASTAL_CITY', '首次亲自建立沿海城市：获得5点中二值，所有城市永久获得+2宜居度。');
