INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text) VALUES
    ('zh_Hans_CN', 'LOC_CIVILIZATION_CHUUNI_SOCIETY_NAME', '极东魔术昼寝结社之夏'),
    ('zh_Hans_CN', 'LOC_CIVILIZATION_CHUUNI_SOCIETY_DESCRIPTION', '极东魔术昼寝结社之夏'),
    ('zh_Hans_CN', 'LOC_CIVILIZATION_CHUUNI_SOCIETY_ADJECTIVE', '极东魔术昼寝结社之夏的'),
    ('zh_Hans_CN', 'LOC_TRAIT_CIVILIZATION_CHUUNI_SOCIETY_NAME', '幻想结社'),
    ('zh_Hans_CN', 'LOC_TRAIT_CIVILIZATION_CHUUNI_SOCIETY_DESCRIPTION', '建立极东魔术昼寝结社并积累中二值。中二值达到1时，军事与宗教战斗力+3；达到20且已创立宗教时提升至+5；达到50且已创立宗教时提升至+8。解锁奇美拉、幻想武装、不可视境界线与魔法阵传送。'),
    ('zh_Hans_CN', 'LOC_LEADER_RIKKA_TAKANASHI_NAME', '小鸟游六花'),
    ('zh_Hans_CN', 'LOC_TRAIT_LEADER_RIKKA_TAKANASHI_NAME', '探索不可视境界线'),
    ('zh_Hans_CN', 'LOC_TRAIT_LEADER_RIKKA_TAKANASHI_DESCRIPTION', 'Schwarz Sechs Prototype Mk II：军事单位防守时+5战斗力；达到第四阶段后主动攻击时+5战斗力。首次亲自建立沿海城市时获得5点中二值，所有城市永久获得+2宜居度。'),
    ('zh_Hans_CN', 'LOC_PEDIA_LEADERS_PAGE_LEADER_RIKKA_TAKANASHI_QUOTE', '爆裂吧，现实！粉碎吧，精神！'),
    ('zh_Hans_CN', 'LOC_LOADING_INFO_LEADER_RIKKA_TAKANASHI', '邪王真眼将揭开不可视境界线。'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_CHUUNI_CLUBROOM', '结社部室'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_CHUUNI_BOUNDARY', '不可视境界线'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_CHUUNI_NAP_HALL', '昼寝会馆'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_CHUUNI_DARK_FLAME', '暗炎城'),
    ('zh_Hans_CN', 'LOC_CITY_NAME_CHUUNI_MAGIC_CIRCLE', '魔法阵之庭'),
    ('zh_Hans_CN', 'LOC_DISTRICT_CHUUNI_SOCIETY_NAME', '极东魔术昼寝结社'),
    ('zh_Hans_CN', 'LOC_DISTRICT_CHUUNI_SOCIETY_DESCRIPTION', '替代圣地并保留圣地的全部基础相邻加成。最终每回合提供2点大预言家点数。每相邻一个学院额外获得+2信仰值；每相邻一个世界奇观额外获得+2信仰值。相邻学院获得+2科技值，剧院广场、娱乐中心和水上乐园获得+2文化值，工业区获得+2生产力。'),
    ('zh_Hans_CN', 'LOC_TRAIT_DISTRICT_CHUUNI_SOCIETY_NAME', '{LOC_DISTRICT_CHUUNI_SOCIETY_NAME}'),
    ('zh_Hans_CN', 'LOC_TRAIT_DISTRICT_CHUUNI_SOCIETY_DESCRIPTION', '{LOC_DISTRICT_CHUUNI_SOCIETY_DESCRIPTION}'),
    ('zh_Hans_CN', 'LOC_BUILDING_CLUB_MAGIC_CIRCLE_NAME', '部室魔法阵'),
    ('zh_Hans_CN', 'LOC_BUILDING_CLUB_MAGIC_CIRCLE_DESCRIPTION', '替代神龛。+2信仰值、+1宜居度、0维护费，并保留神龛的1点大预言家点数。'),
    ('zh_Hans_CN', 'LOC_TRAIT_BUILDING_CLUB_MAGIC_CIRCLE_NAME', '{LOC_BUILDING_CLUB_MAGIC_CIRCLE_NAME}'),
    ('zh_Hans_CN', 'LOC_TRAIT_BUILDING_CLUB_MAGIC_CIRCLE_DESCRIPTION', '{LOC_BUILDING_CLUB_MAGIC_CIRCLE_DESCRIPTION}'),
    ('zh_Hans_CN', 'LOC_CHUUNI_SOCIETY_FROM_CAMPUS_FAITH_DESCRIPTION', '+{1_Num}信仰值，来自每个相邻的学院。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_SOCIETY_FROM_WONDER_FAITH_DESCRIPTION', '+{1_Num}信仰值，来自每个相邻的世界奇观。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_SOCIETY_TO_SCIENCE_DESCRIPTION', '+{1_Num}科技值，来自相邻极东魔术昼寝结社。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_SOCIETY_TO_CULTURE_DESCRIPTION', '+{1_Num}文化值，来自相邻极东魔术昼寝结社。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_SOCIETY_TO_PRODUCTION_DESCRIPTION', '+{1_Num}生产力，来自相邻极东魔术昼寝结社。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_FANTASY_COMBAT_STAGE_1_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自幻想第一阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_FANTASY_COMBAT_STAGE_2_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自幻想第二阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_FANTASY_COMBAT_STAGE_3_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自幻想第三阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_FANTASY_COMBAT_STAGE_4_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自幻想第四阶段'),
    ('zh_Hans_CN', 'LOC_RESOURCE_CHUUNI_STAGE_MARKER_1_NAME', '幻想第一阶段标记'),
    ('zh_Hans_CN', 'LOC_RESOURCE_CHUUNI_STAGE_MARKER_2_NAME', '幻想第二阶段标记'),
    ('zh_Hans_CN', 'LOC_RESOURCE_CHUUNI_STAGE_MARKER_3_NAME', '幻想第三阶段标记'),
    ('zh_Hans_CN', 'LOC_RESOURCE_CHUUNI_STAGE_MARKER_4_NAME', '幻想第四阶段标记'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STAGE_1_UNLOCKED', '中二值达到1：幻想第一阶段已解锁。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STAGE_2_UNLOCKED', '中二值达到20且已创立宗教：幻想第二阶段已解锁。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STAGE_3_UNLOCKED', '中二值达到50且已创立宗教：幻想第三阶段已解锁。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STAGE_4_UNLOCKED', '中二值达到100且已创立宗教：幻想第四阶段已解锁。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_TITLE', '中二值'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_VALUE_FORMAT', '中二值：{1_Value}/100'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_FORMAT', '当前阶段：{1_Stage}'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_NEXT_FORMAT', '下一阶段：{1_Value}'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_MAX_STAGE', '已达到第四阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_0_NAME', '尚未觉醒'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_1_NAME', '第一阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_2_NAME', '第二阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_3_NAME', '第三阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_4_NAME', '第四阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_ABILITY_TITLE', '当前阶段能力'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_0_ABILITY', '尚未获得幻想战斗加成。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_1_ABILITY', '军事单位+3战斗力；宗教单位+3宗教战斗力。[NEWLINE]解锁奇美拉总督。奇美拉建立后：特色结社与部室魔法阵+100%生产力；每10点中二值使该城市+1信仰，最多+10；在其城市领土内正常休整的单位额外恢复20生命值。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_2_ABILITY', '军事单位与宗教单位的战斗力合计提升至+5。奇美拉城市领土内单位额外+5战斗力，城市每10点中二值+1文化。幻想武装：升级金币-25%、战略资源-50%。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_3_ABILITY', '军事单位与宗教单位的战斗力合计提升至+8。奇美拉城市领土内开始回合的单位+1移动力、+1视野，城市每10点中二值+1科技。幻想武装：升级金币-50%、战略资源-50%。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_4_ABILITY', '幻想战斗加成维持+8；六花的军事单位主动攻击时+5战斗力。幻想武装升级免费且不消耗战略资源。所有部室魔法阵城市+5信仰、+5文化、+5科技。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_UNMET_TITLE', '未满足条件'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_UNMET_VALUE', '还需{1_Value}点中二值。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_UNMET_RELIGION', '尚未创立宗教。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_ALL_MET', '下一阶段条件已经满足，将在阶段状态刷新时解锁。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_BUTTON_TOOLTIP', '中二值：{1_Value}/100[NEWLINE]点击查看详情。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_POPUP_TITLE', '中二值与幻想阶段'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_CURRENT_VALUE', '当前中二值：{1_Value}/100'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_CURRENT_STAGE', '当前阶段：{1_Stage}'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_CURRENT_ABILITY', '当前能力：'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_NEXT_STAGE', '下一阶段：{1_Stage}'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_REQUIRED_VALUE', '所需中二值：{1_Value}'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_RELIGION_MET', '创立宗教：已满足。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_OVERVIEW', '四阶段总览'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_OVERVIEW_LINE', '{1_State} {2_Stage}（{3_Value}）：{4_Ability}'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_LOCKED', '[未解锁]'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_UNLOCKED', '[已解锁]'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_STAGE_CURRENT', '[当前]'),
    ('zh_Hans_CN', 'LOC_CHUUNI_STATUS_CLOSE', '关闭'),
    ('zh_Hans_CN', 'LOC_CHUUNI_FIRST_COASTAL_CITY', '首次亲自建立沿海城市：获得5点中二值，所有城市永久获得+2宜居度。');

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text) VALUES
    ('zh_Hans_CN', 'LOC_GOVERNOR_CHIMERA_NAME', '奇美拉'),
    ('zh_Hans_CN', 'LOC_GOVERNOR_CHIMERA_TITLE', '幻想结社管理者'),
    ('zh_Hans_CN', 'LOC_GOVERNOR_CHIMERA_SHORT_TITLE', '奇美拉'),
    ('zh_Hans_CN', 'LOC_GOVERNOR_CHIMERA_DESCRIPTION', '中二值达到第一阶段后免费任命。建立与调任仅需1回合。能力随幻想阶段逐步解锁，并只作用于督管城市及其领土。'),
    ('zh_Hans_CN', 'LOC_GOVERNOR_PROMOTION_CHIMERA_BASE_NAME', '幻想结社'),
    ('zh_Hans_CN', 'LOC_GOVERNOR_PROMOTION_CHIMERA_BASE_DESCRIPTION', '第一阶段：特色结社和部室魔法阵+100%生产力；每10点中二值+1信仰；正常休整额外恢复20生命。第二阶段：领土内单位+5战斗力，每10点中二值+1文化。第三阶段：领土内开始回合的单位+1移动力、+1视野，每10点中二值+1科技。第四阶段：所有部室魔法阵城市+5信仰、文化和科技。');

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text) VALUES
    ('zh_Hans_CN', 'LOC_RIKKA_SCHWARZ_SECHS_DEFENSE_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自 Schwarz Sechs 防守姿态'),
    ('zh_Hans_CN', 'LOC_RIKKA_SCHWARZ_SECHS_ATTACK_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自 Schwarz Sechs 第四阶段'),
    ('zh_Hans_CN', 'LOC_ABILITY_CHUUNI_CHIMERA_COMBAT_NAME', '奇美拉：幻想战斗'),
    ('zh_Hans_CN', 'LOC_ABILITY_CHUUNI_CHIMERA_COMBAT_DESCRIPTION', '位于奇美拉督管城市领土内时+5战斗力或宗教战斗力。'),
    ('zh_Hans_CN', 'LOC_ABILITY_CHUUNI_CHIMERA_MOBILITY_NAME', '奇美拉：境界机动'),
    ('zh_Hans_CN', 'LOC_ABILITY_CHUUNI_CHIMERA_MOBILITY_DESCRIPTION', '在奇美拉督管城市领土内开始回合时，本回合+1移动力、+1视野。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_CHIMERA_COMBAT_PREVIEW', '+{1_Amount} [ICON_Strength] 战斗力来自奇美拉督管城市'),
    ('zh_Hans_CN', 'LOC_IMPROVEMENT_INVISIBLE_BOUNDARY_NAME', '不可视境界线'),
    ('zh_Hans_CN', 'LOC_IMPROVEMENT_INVISIBLE_BOUNDARY_DESCRIPTION', '制图学解锁。只能由建造者修建在海洋上，每座城市限1个，不能相邻且无法被掠夺。每个相邻海洋提供+1科技和+1生产力；每个相邻海岸提供+1信仰和+1食物。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_BOUNDARY_OCEAN_SCIENCE_DESCRIPTION', '+{1_Num}科技值，来自每个相邻海洋。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_BOUNDARY_OCEAN_PRODUCTION_DESCRIPTION', '+{1_Num}生产力，来自每个相邻海洋。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_BOUNDARY_COAST_FAITH_DESCRIPTION', '+{1_Num}信仰值，来自每个相邻海岸。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_BOUNDARY_COAST_FOOD_DESCRIPTION', '+{1_Num}食物，来自每个相邻海岸。'),
    ('zh_Hans_CN', 'LOC_CHUUNI_TELEPORT_NEAREST', '将当前单位传送至最近的部室魔法阵');
